name: build-windows-exe
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'   # matches their doc
          architecture: 'x64'

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install nuitka pyqt5
          if (Test-Path requirements.txt) { python -m pip install -r requirements.txt }

      - name: Build with Nuitka
        shell: pwsh
        run: |
          python -m nuitka `
            --onefile `
            --standalone `
            --enable-plugin=pyqt5 `
            --remove-output `
            --windows-console-mode=disable `
            --windows-uac-admin `
            --output-dir=dist `
            --windows-icon-from-ico=media/ICON.ico `
            --include-data-dir=configs=configs `
            --include-data-dir=media=media `
            --include-package=screens `
            --assume-yes-for-downloads `
            talon.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: talon-exe
          path: dist/**
